### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by YouXam** [mzdluo123/MiraiAndroid#20]
[日志](https://paste.ubuntu.com/p/nRg4BhS3Yw/)

设备: HUAWEI M6

Android 版本: 9

**Comment by mzdluo123** [comment]
上一个版本(2.2)有这个问题吗？

**Comment by YouXam** [comment]
2.2有同样的问题, 但2.1没有 可以正常登录

另外, 无法弹出登录验证码, 必须分享日志之后复制地址验证后才可以登录

如果新版本中也是这样, 建议增加弹出浏览器 和**复制日志**的功能

**Comment by mzdluo123** [comment]
登录弹出验证码和扫码验证是完全正常的，请点击弹出的通知登录

日志更多时候是用来给我们排除错误的，因此直接上传到Ubuntu pastebin更有助于我们定位问题

关于无法登录的问题稍后修复
