### ISSUE TITLE
安卓6.0手机并不能安装releases里的apk

### ISSUE THREAD

**Issue by I-love-study** [mzdluo123/MiraiAndroid#26]
系统是基于安卓6.0的Flyme 7.8.7.24 beta
复制到手机里面安装不行
使用adb又显示系统版本太低
明明readme写了支持安卓6.0来着。。

![S00620-010045](https://user-images.githubusercontent.com/39652142/85161235-0e1d6c00-b292-11ea-88be-99f289327b7b.jpg)
![image](https://user-images.githubusercontent.com/39652142/85161317-2bead100-b292-11ea-8328-2f785f687556.png)
![S00620-010207(1)](https://user-images.githubusercontent.com/39652142/85161249-12e22000-b292-11ea-98d7-85435a927fa2.jpg)

**Comment by mzdluo123** [comment]
方便提供一下你的设备用于测试吗？目前我们无法确认程序能在Android6.0上正常运行，如果可以请到交流群内联系我们

**Comment by I-love-study** [comment]
很抱歉因为本人是学生(工作日住宿没有电子设备)并不能长时间在线
所以可能会出现突然失联的状态
不过用于测试的话我还是乐意的
