### ISSUE TITLE
电脑编译完的MiraiAPIHTTP在ma还是报错

### ISSUE THREAD

**Issue by I-love-study** [mzdluo123/MiraiAndroid#29]
[https://paste.ubuntu.com/p/gM7jvvkFTB/](https://paste.ubuntu.com/p/gM7jvvkFTB/)
MiraiAPIHTTP 1.7.3在电脑上使用d8编译的，放在ma里，报错
同样在电脑上编译的CQHTTPMirai 0.1.4却没有报错
也试过群文件中httpapi-android.jar
但还是报错

**Comment by mzdluo123** [comment]
额，这是一个兼容性问题，Android6.0不兼容部分Java8特性导致了这个问题，目前并没有好的解决方法

**Comment by mzdluo123** [comment]
这个问题等到新console出现也不会得到解决，由于目前老旧Android6.0设备占有量较高，考虑兼容
