### ISSUE TITLE
自动登录密码错误的boom

### ISSUE THREAD

**Issue by LXY1226** [mzdluo123/MiraiAndroid#3]
如题...

[crashlog.log](https://github.com/mzdluo123/MiraiAndroid/files/4590304/crashlog.log)

**Comment by LXY1226** [comment]
`L1977 2020-05-07 10:08:15.337 2479-2525/? D/io.github.mzdluo123.mirai.android.AndroidLoginSolver: [NETWORK] Packet: Error(title=登录失败, message=帐号或密码错误，请重新输入。, errorInfo=)
L1978 2020-05-07 10:08:15.338 2479-2525/? D/io.github.mzdluo123.mirai.android.AndroidLoginSolver: [INFO] **null**
L1979 2020-05-07 10:08:15.338 2479-2525/? D/io.github.mzdluo123.mirai.android.AndroidLoginSolver: [BOT ERROR 3215463081] net.mamoe.mirai.network.WrongPasswordException: Error(title=登录失败, message=帐号或密码错误，请重新输入。, errorInfo=)`

**Comment by mzdluo123** [comment]
已修复
