### ISSUE TITLE
mirai-plugins库内所有插件在安卓8.1.0设备全部无法编译

### ISSUE THREAD

**Issue by feilongproject** [mzdluo123/MiraiAndroid#35]
如图，在[https://github.com/project-mirai/mirai-plugins](https://github.com/project-mirai/mirai-plugins) 库内所有插件均无法安装，都会编译失败，而不是readme里所说的"部分"（测试了约20+个插件，加上每个插件的各个版本约80+）
![Screenshot_20200817_231802](https://user-images.githubusercontent.com/43880786/90415830-3ab00180-e0e4-11ea-9476-d5d25308df97.jpg)

设备：vivo y93 v1818a
系统：安卓8.1.0

**Comment by mzdluo123** [comment]
这是预期的情况，我已经在readme里说明了。
且目前并没有很好的解决方案，后续可能会修复，请关注changelog
