### ISSUE TITLE
[BUG]miui12 验证登录通知栏在不重要里面

### ISSUE THREAD

**Issue by yuWorm** [mzdluo123/MiraiAndroid#50]
在miui12中，验证登录通知栏在不重要通知当中

```



```

**Comment by yiyungent** [comment]
我也出现了这个问题，
权限管理：常驻通知：始终允许
Redmi K30 Ultra
MIUI 12.5.3

然而 终端提示本次登录需要进行验证，
通知栏确实有个 "MiraiAndroid： 请完成登录并将软件...`，不过点击了后就是返回了软件，
当然我也锁定了后台，开启了自启动

**Comment by yiyungent** [comment]
解决：
长按 `MiraiAndroid`一直都在的那个通知，
点击 `更多设置`，

`通知过滤规则` -> `全部设为重要`
