### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by fatinghenji** [mzdluo123/MiraiAndroid#58]
#### 我做了什么？
- [x] 阅读了使用文档
- [ ] 重新看了一遍Wiki   :see_no_evil:~~没看到本项目有Wiki~~
- [x] 尝试使用了最新版本
- [x] 尝试了在已有的issue里面找答案  
-  没有看到相关的issue
- [x] 去问谷歌/度娘  
- 在Mirai论坛里请求帮助没有找到答案，参见：[使用d8.bat转换jar时遇到的问题](https://mirai.mamoe.net/topic/209/%E4%BD%BF%E7%94%A8d8-bat%E8%BD%AC%E6%8D%A2jar%E6%97%B6%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98) 
#### 使用环境
- [x] Android Build Tool：build-tools_r30.0.1-windows
- [x] java version ：1.8.0_191
- [x] 电脑端：Windows10
#### 使用代码如下
```ruby
d8.bat --output aknights-helper.jar C:\Users\abc\Downloads\arknights-helper-1.0.0-dev-1.mirai.jar
```
```ruby
d8.bat C:\Users\abc\Downloads\arknights-helper-1.0.0-dev-1.mirai.jar --output aknights-helper.jar
```
#### 已经尝试的方案：
- [x] 更改命令
#### 当前结果 
:skull:没有生成新的jar文件
#### 期望目标
:sparkling_heart:生成可用的jar文件

**Comment by cssxsh** [comment]
d8.bat 需要java 环境支持，并且 如果是高版本java 可能还需要修改 d8.bat 文件

**Comment by mzdluo123** [comment]
最近在期末考，考完我来看看

**Comment by fatinghenji** [comment]
### 问题解决了
#### 解决方法
1、右键d8.bat文件，以记事本形式打开。
2、找到如下代码
```ruby
rem Check we have a valid Java.exe in the path.
set java_exe=
if exist    "%~dp0..\tools\lib\find_java.bat" call    "%~dp0..\tools\lib\find_java.bat"
if exist "%~dp0..\..\tools\lib\find_java.bat" call "%~dp0..\..\tools\lib\find_java.bat"
if not defined java_exe goto :EOF
```
3、在```set java_exe=```中填写Java的安装地址
4、保存文件
### 需要注意
- 编译命令从```d8.bat --output 输出文件.jar 源文件```更改为```d8.bat 源文件 --output 输出文件.jar ```
