### ISSUE TITLE
无法登陆qq

### ISSUE THREAD

**Issue by H1W0XXX** [mzdluo123/MiraiAndroid#62]
不能扫码登录qq了，只能填写资料验证，资料全写对也提示资料错误，填写的资料有 绑定的手机号、头像、登录的设备名称。
换了好几个账号都是这样。

**Comment by mzdluo123** [comment]
确认你使用的是不是最新版

**Comment by H1W0XXX** [comment]
用最新版321会导致http协议插件不能正常工作，我就退回320了，退回以后就登陆不上账号了

**Comment by mzdluo123** [comment]
更新，然后等httpapi适配。你也可以在新版登录后复制设备文件到旧版

**Comment by H1W0XXX** [comment]
好的
