### ISSUE TITLE
[BUG]最新版导出的DEVICE.JSON文件无法使用

### ISSUE THREAD

**Issue by hu1240050829** [mzdluo123/MiraiAndroid#72]
我用miraiAndroid登录成功之后，最新的兼容版导出device.json文件，无法放到mira里面配置使用，用之前3.2.2版本的是可以的，现在3.2.2版本的app也找不到了

**Comment by hu1240050829** [comment]
> 普通版呢？兼容版存在大量问题暂时停止更新

由于暂时找不到支持8.0的虚拟机，暂时还没有试过

**Comment by mzdluo123** [comment]
我试试给你编译一个兼容版看看，不过并不能保证他能工作

**Comment by mzdluo123** [comment]
https://cowtransfer.com/s/42ec21d1e83d43

767394
