### ISSUE TITLE
Plugins 加载文件 在哪？

### ISSUE THREAD

**Issue by greenhandzdl** [mzdluo123/MiraiAndroid#79]
对于出错导致无法init mirai-console的plugins，我优先删除掉该出问题的plugin。
但是，有一天，我发现plugin删掉之后重启依然加载了该plugin导致报错，而将plugin放到另一台设备的mirai时，发现无报错。
所以，配置文件到底在哪儿？
![Screenshot_2022-01-28-00-16-42-337_io.github.mzdluo123.mirai.android.jpg](https://user-images.githubusercontent.com/61241103/151399233-fb17b208-792e-43f4-9060-42403ee5941c.jpg)![IMG_20220128_001747.jpg](https://user-images.githubusercontent.com/61241103/151399246-fbad27be-2c7b-499a-8fd1-b75b44cb3842.jpg)

**Comment by mzdluo123** [comment]
也许是应用内自带删除出现了问题？可以去文件管理器看看，路径在启动时会打印

**Comment by greenhandzdl** [comment]
嗯，/config/Console所有都可以删，大致是这个问题

**Comment by mzdluo123** [comment]
确定是应用内置删除的问题吗？如果是的话你可以重新打开issue并更改标题，有空我会尝试修复
